<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Alternativas' => $baseDir . '/model/Alternativas.class.php',
    'Avaliacoes' => $baseDir . '/model/Avaliacoes.class.php',
    'Categorias' => $baseDir . '/model/Categorias.class.php',
    'Competencias' => $baseDir . '/model/Competencias.class.php',
    'Conexao' => $baseDir . '/model/Conexao.class.php',
    'Config' => $baseDir . '/model/Config.class.php',
    'Cursos' => $baseDir . '/model/Cursos.class.php',
    'Disciplinas' => $baseDir . '/model/Disciplinas.class.php',
    'DisciplinasAvaliacao' => $baseDir . '/model/DisciplinasAvaliacao.class.php',
    'ImageUpload' => $baseDir . '/model/ImageUpload.class.php',
    'Login' => $baseDir . '/model/Login.class.php',
    'Noticias' => $baseDir . '/model/Noticias.class.php',
    'Paginacao' => $baseDir . '/model/Paginacao.class.php',
    'Perfis' => $baseDir . '/model/Perfis.class.php',
    'Questoes' => $baseDir . '/model/Questoes.class.php',
    'Rotas' => $baseDir . '/model/Rotas.class.php',
    'Sistema' => $baseDir . '/model/Sistema.class.php',
    'Template' => $baseDir . '/model/Template.class.php',
);
